version: '3.8'

x-local-volumes:
  - &python_packages-volume '../../../python_packages:/home/app/python_packages:delegated'
  - &app-volume './:/home/app/:delegated'
  # in dev, django_external_field ExternalField values are saved locally to the MEDIA_ROOT dir instead of S3, remove if you are not using ExternalField
  - &media-volume './certtool/media:/home/app/certtool/media:delegated'

services:
  certtool:
    volumes:
      - *app-volume
      - *media-volume
      - *python_packages-volume
    depends_on:
      - localstack
  localstack:
    container_name: localstack
    image: public.ecr.aws/localstack/localstack:1.4
    healthcheck:
      test: awslocal kms list-keys
      interval: 10s
      timeout: 30s
    ports:
      - 4566            # LocalStack Gateway
      - "4510-4559"
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=kms

