# Generated by Django 4.2.2 on 2023-06-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificateModel",
            fields=[
                (
                    "certificate_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("acm_arn", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "private_ca_arn",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "issuer_ca_arn",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "subject_common_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "subject_country",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "subject_state",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "subject_locality",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "subject_ogranization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subject_organizational_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subject_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("certificate_pem", models.TextField()),
                ("chain_pem", models.TextField(blank=True, null=True)),
                ("csr_pem", models.TextField(blank=True, null=True)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                (
                    "key_reference",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("EXPIRED", "EXPIRED"),
                            ("REVOKED", "REVOKED"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagsModel",
            fields=[
                ("tag_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tag_key", models.CharField(max_length=255)),
                ("tag_value", models.CharField(max_length=255)),
                (
                    "certificate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certtool_api.certificatemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectAlternateNameModel",
            fields=[
                (
                    "alternate_name_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("alternate_name", models.CharField(max_length=255)),
                (
                    "certificate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certtool_api.certificatemodel",
                    ),
                ),
            ],
        ),
    ]
